version: '3.8'
services:
  front:
    container_name: seekers-mail-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      my_network:
        ipv4_address: 172.28.0.10

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
