name: linters

on:
  push:
    branches: [ 'main', 'dev/**' ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name:  Install deps
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Stylelint
        run: npm run stylelint
